### ISSUE TITLE
Why and how to use this package?

### ISSUE THREAD

**Issue by JoseCage** [Morning-Train/laravel-https#1]
Hello @bbMorningtrain 

Can you please explain how/where and/or why to use **laravel-https** package?

![image](https://cloud.githubusercontent.com/assets/4200487/21622777/7b8f0c0c-d1ff-11e6-93b6-2496d685d244.png)

**Comment by SteenSchutt** [comment]
You just need to follow the two steps in the readme and add USE_SSL=true to `.env` and then it will enforce SSL on your Laravel site.

**Comment by JoseCage** [comment]
Really nice.. Thanks @DoctorBlue
